Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 445B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.9
#2 DONE 1.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.9@sha256:1446afd121c574b13077f4137443114cd8085f1dade5ee63c08305b5870f2b8a
#4 resolve docker.io/library/python:3.9@sha256:1446afd121c574b13077f4137443114cd8085f1dade5ee63c08305b5870f2b8a 0.0s done
#4 sha256:1446afd121c574b13077f4137443114cd8085f1dade5ee63c08305b5870f2b8a 1.86kB / 1.86kB done
#4 sha256:4c48c04d1fb3009c52c336e056f902701a669fb1a0dcf7b31eecaa5902e4b624 2.01kB / 2.01kB done
#4 sha256:c94ad86caa0c383c0bb1696f9d16b1efcb6aec23d334977bb6bd9e034f1658aa 7.31kB / 7.31kB done
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 0B / 15.82MB 0.2s
#4 sha256:bf7985fdee5c6bc4ef85f9f7632a4e68eef4d3903f45abb2ad7918afd35ac906 0B / 2.85MB 0.2s
#4 sha256:b48a26c2e793d41d2af3d848f1857a70988240cc7ed68065bf2163615b4953e7 0B / 243B 0.2s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 1.05MB / 15.82MB 0.8s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 2.10MB / 15.82MB 1.2s
#4 sha256:b48a26c2e793d41d2af3d848f1857a70988240cc7ed68065bf2163615b4953e7 243B / 243B 1.1s done
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 3.15MB / 15.82MB 1.8s
#4 sha256:bf7985fdee5c6bc4ef85f9f7632a4e68eef4d3903f45abb2ad7918afd35ac906 1.05MB / 2.85MB 2.4s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 4.19MB / 15.82MB 2.6s
#4 sha256:bf7985fdee5c6bc4ef85f9f7632a4e68eef4d3903f45abb2ad7918afd35ac906 2.10MB / 2.85MB 3.0s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 5.24MB / 15.82MB 3.1s
#4 sha256:bf7985fdee5c6bc4ef85f9f7632a4e68eef4d3903f45abb2ad7918afd35ac906 2.85MB / 2.85MB 3.5s done
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 6.29MB / 15.82MB 3.7s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 7.34MB / 15.82MB 4.0s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 8.39MB / 15.82MB 4.5s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 9.44MB / 15.82MB 4.7s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 10.49MB / 15.82MB 5.0s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 11.53MB / 15.82MB 5.5s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 12.58MB / 15.82MB 5.6s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 13.63MB / 15.82MB 6.0s
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 14.68MB / 15.82MB 6.2s
#4 extracting sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58
#4 sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 15.82MB / 15.82MB 6.4s done
#4 extracting sha256:6d3d7d17de07b8f1f6be6f9edd43bce3ac0f043209f192ee7be60c6e301c7c58 0.5s done
#4 extracting sha256:b48a26c2e793d41d2af3d848f1857a70988240cc7ed68065bf2163615b4953e7 done
#4 extracting sha256:bf7985fdee5c6bc4ef85f9f7632a4e68eef4d3903f45abb2ad7918afd35ac906 0.1s
#4 extracting sha256:bf7985fdee5c6bc4ef85f9f7632a4e68eef4d3903f45abb2ad7918afd35ac906 0.2s done
#4 DONE 7.5s

#5 [2/6] WORKDIR /app
#5 DONE 0.1s

#6 [3/6] RUN git clone https://github.com/home-assistant/core.git
#6 0.292 Cloning into 'core'...
#6 DONE 246.8s

#7 [4/6] WORKDIR /app/core
#7 DONE 0.1s

#8 [5/6] RUN pip install -r requirements.txt
#8 1.619 Collecting aiodns==3.2.0
#8 1.680   Downloading aiodns-3.2.0-py3-none-any.whl (5.7 kB)
#8 2.279 Collecting aiohttp==3.9.5
#8 2.294   Downloading aiohttp-3.9.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
#8 2.889      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.1 MB/s eta 0:00:00
#8 2.933 Collecting aiohttp_cors==0.7.0
#8 2.965   Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
#8 3.255 Collecting aiohttp_session==2.12.0
#8 3.277   Downloading aiohttp_session-2.12.0-py3-none-any.whl (12 kB)
#8 3.536 Collecting aiohttp-fast-url-dispatcher==0.3.0
#8 3.551   Downloading aiohttp_fast_url_dispatcher-0.3.0-py3-none-any.whl (8.9 kB)
#8 3.818 Collecting aiohttp-fast-zlib==0.1.0
#8 3.832   Downloading aiohttp_fast_zlib-0.1.0-py3-none-any.whl (8.2 kB)
#8 3.879 Collecting astral==2.2
#8 3.892   Downloading astral-2.2-py2.py3-none-any.whl (30 kB)
#8 4.150 Collecting async-interrupt==1.1.1
#8 4.164   Downloading async_interrupt-1.1.1-py3-none-any.whl (8.9 kB)
#8 4.217 Collecting attrs==23.2.0
#8 4.246   Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
#8 4.305      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 1.7 MB/s eta 0:00:00
#8 4.568 Collecting atomicwrites-homeassistant==1.4.1
#8 4.589   Downloading atomicwrites_homeassistant-1.4.1-py2.py3-none-any.whl (7.1 kB)
#8 4.841 Collecting awesomeversion==24.2.0
#8 4.851   Downloading awesomeversion-24.2.0-py3-none-any.whl (13 kB)
#8 4.976 Collecting bcrypt==4.1.2
#8 4.987   Downloading bcrypt-4.1.2-cp39-abi3-manylinux_2_28_x86_64.whl (698 kB)
#8 5.306      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 698.9/698.9 kB 2.2 MB/s eta 0:00:00
#8 5.354 Collecting certifi>=2021.5.30
#8 5.364   Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
#8 5.443      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 2.1 MB/s eta 0:00:00
#8 5.753 Collecting ciso8601==2.3.1
#8 5.858   Downloading ciso8601-2.3.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38 kB)
#8 6.151 Collecting fnv-hash-fast==0.5.0
#8 6.215   Downloading fnv_hash_fast-0.5.0.tar.gz (5.8 kB)
#8 6.239   Installing build dependencies: started
#8 11.27   Installing build dependencies: finished with status 'done'
#8 11.28   Getting requirements to build wheel: started
#8 11.34   Getting requirements to build wheel: finished with status 'done'
#8 11.34   Preparing metadata (pyproject.toml): started
#8 11.53   Preparing metadata (pyproject.toml): finished with status 'done'
#8 11.61 ERROR: Cannot install hass-nabucasa==0.81.0 because these package versions have conflicting dependencies.
#8 11.61 
#8 11.61 The conflict is caused by:
#8 11.61     The user requested hass-nabucasa==0.81.0
#8 11.61     The user requested (constraint) hass-nabucasa==0.81.0
#8 11.61 
#8 11.61 To fix this you could try to:
#8 11.61 1. loosen the range of package versions you've specified
#8 11.61 2. remove package versions to allow pip attempt to solve the dependency conflict
#8 11.61 
#8 11.61 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
#8 11.61 
#8 11.61 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 11.61 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [5/6] RUN pip install -r requirements.txt:
11.61     The user requested (constraint) hass-nabucasa==0.81.0
11.61 
11.61 To fix this you could try to:
11.61 1. loosen the range of package versions you've specified
11.61 2. remove package versions to allow pip attempt to solve the dependency conflict
11.61 
11.61 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
11.61 
11.61 [notice] A new release of pip is available: 23.0.1 -> 24.0
11.61 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:14
--------------------
  12 |     
  13 |     # Install the necessary dependencies
  14 | >>> RUN pip install -r requirements.txt
  15 |     
  16 |     # Run the tests to verify installation
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
machine already startedTEMP DIR: /tmp/tmp.a3Jv1O5W21Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 469B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/6] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 2B done
#6 DONE 0.2s

#7 [3/6] RUN git clone https://github.com/home-assistant/core.git
#7 ...

#8 [4/6] WORKDIR /app/core
#8 CACHED

#9 [5/6] COPY requirements_test.txt .
#9 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::kxrcko5wzcb556cgwhlkmlvje: "/requirements_test.txt": not found

#7 [3/6] RUN git clone https://github.com/home-assistant/core.git
#7 0.354 Cloning into 'core'...
#7 CANCELED
------
 > [5/6] COPY requirements_test.txt .:
------
Dockerfile:14
--------------------
  12 |     
  13 |     # Install any necessary dependencies
  14 | >>> COPY requirements_test.txt .
  15 |     RUN pip install --no-cache-dir -r requirements_test.txt
  16 |     
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::kxrcko5wzcb556cgwhlkmlvje: "/requirements_test.txt": not found
removing docker image...clearing temp directorymachine already started
TEMP DIR: /tmp/tmp.xR2JemSYgg


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 450B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/6] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 2B 0.0s done
#6 DONE 0.2s

#7 [3/6] RUN git clone https://github.com/home-assistant/core.git .
#7 ...

#8 [4/6] COPY requirements.txt .
#8 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::u7zuc4v1ylu5hwu38l7q11cky: "/requirements.txt": not found

#7 [3/6] RUN git clone https://github.com/home-assistant/core.git .
#7 0.423 runc run failed: container process is already dead
#7 CANCELED
------
 > [4/6] COPY requirements.txt .:
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Copy the requirements file into the container
  11 | >>> COPY requirements.txt .
  12 |     
  13 |     # Install any dependencies
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::u7zuc4v1ylu5hwu38l7q11cky: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.WRyvJCphJM


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 424B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3
#2 DONE 1.6s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6
#4 resolve docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6 0.1s done
#4 ...

#5 [internal] load build context
#5 transferring context: 424B done
#5 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3@sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6
#4 sha256:3966b81808d864099f802080d897cef36c01550472ab3955fdd716d1c665acd6 2.14kB / 2.14kB done
#4 sha256:76831bb094456f98613115be37cc8d4f9ab0d128467726ed3160044c80546437 2.01kB / 2.01kB done
#4 sha256:12e5ab9d51c883bedc4db6c7cbc49f3fa97aef4e98dc205bf1c67e21fd9cb6f4 7.10kB / 7.10kB done
#4 sha256:4429b810e09ef699c3034e49b60f85add3610968983af403fb3181255a5b639f 0B / 243B 0.2s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 0B / 22.69MB 0.2s
#4 sha256:2a4ca5af09fa6cc704c04ba61e304cbf3d0fb2c55f52bf8c8dcba14651216c17 0B / 2.77MB 0.2s
#4 sha256:4429b810e09ef699c3034e49b60f85add3610968983af403fb3181255a5b639f 243B / 243B 0.8s done
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 2.10MB / 22.69MB 1.2s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 4.19MB / 22.69MB 2.2s
#4 sha256:2a4ca5af09fa6cc704c04ba61e304cbf3d0fb2c55f52bf8c8dcba14651216c17 1.05MB / 2.77MB 2.2s
#4 sha256:2a4ca5af09fa6cc704c04ba61e304cbf3d0fb2c55f52bf8c8dcba14651216c17 2.10MB / 2.77MB 3.0s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 6.29MB / 22.69MB 3.2s
#4 sha256:2a4ca5af09fa6cc704c04ba61e304cbf3d0fb2c55f52bf8c8dcba14651216c17 2.77MB / 2.77MB 3.4s done
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 8.39MB / 22.69MB 3.8s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 10.49MB / 22.69MB 4.6s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 12.58MB / 22.69MB 5.1s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 14.68MB / 22.69MB 5.5s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 16.78MB / 22.69MB 6.3s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 18.87MB / 22.69MB 6.8s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 20.97MB / 22.69MB 7.4s
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 22.69MB / 22.69MB 7.8s
#4 extracting sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005
#4 sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 22.69MB / 22.69MB 7.8s done
#4 extracting sha256:d46a03def8d9bd846f37fee0edc9fcb7400d68166e99f039cd87b99948af6005 0.6s done
#4 extracting sha256:4429b810e09ef699c3034e49b60f85add3610968983af403fb3181255a5b639f done
#4 extracting sha256:2a4ca5af09fa6cc704c04ba61e304cbf3d0fb2c55f52bf8c8dcba14651216c17
#4 extracting sha256:2a4ca5af09fa6cc704c04ba61e304cbf3d0fb2c55f52bf8c8dcba14651216c17 0.2s done
#4 DONE 9.1s

#6 [2/4] WORKDIR /app
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.2s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.496 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.496 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite of the repository
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.xVSBOEN0aX


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 400B done
#1 DONE 0.1s

#2 [auth] library/python:pull token for registry-1.docker.io
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/python:3.8
#3 DONE 1.5s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.1s

#5 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#5 DONE 0.0s

#6 [2/4] WORKDIR /app
#6 CACHED

#7 [internal] load build context
#7 transferring context: 400B done
#7 DONE 0.1s

#8 [3/4] COPY . /app
#8 DONE 0.1s

#9 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#9 2.436 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#9 2.653 
#9 2.653 [notice] A new release of pip is available: 23.0.1 -> 24.0
#9 2.653 [notice] To update, run: pip install --upgrade pip
#9 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
2.436 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
2.653 
2.653 [notice] A new release of pip is available: 23.0.1 -> 24.0
2.653 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.xPOY1Gf0d0


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 407B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 407B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.227 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.389 
#8 1.389 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.389 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.227 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.389 
1.389 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.389 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.X8U0Wr6jRz


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 422B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 422B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.257 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.399 
#8 1.399 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.399 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.257 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.399 
1.399 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.399 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Define the command to run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.yFZT0Ca3bN


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 415B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 415B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.325 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.438 
#8 1.438 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.438 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.325 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.438 
1.438 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.438 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.Xok5F0FIO6


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 405B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 405B done
#6 DONE 0.1s

#7 [3/4] COPY . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install --no-cache-dir -r requirements.txt
#8 1.301 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 1.498 
#8 1.498 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 1.498 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install --no-cache-dir -r requirements.txt:
1.301 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
1.498 
1.498 [notice] A new release of pip is available: 23.0.1 -> 24.0
1.498 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any dependencies specified in requirements.txt
  11 | >>> RUN pip install --no-cache-dir -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.OjAZej6H4x


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 556B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/7] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/7] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 2B done
#6 DONE 0.1s

#7 [3/7] COPY requirements.txt .
#7 ERROR: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::3td16q074o6ej2sfzzgmi9jtw: "/requirements.txt": not found
------
 > [3/7] COPY requirements.txt .:
------
Dockerfile:8
--------------------
   6 |     
   7 |     # Copy the requirements file into the container
   8 | >>> COPY requirements.txt .
   9 |     
  10 |     # Install the project dependencies
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 40bc7d34-f251-4a8c-9b64-40dd406c9169::3td16q074o6ej2sfzzgmi9jtw: "/requirements.txt": not found
removing docker image...
clearing temp directory
machine already started
TEMP DIR: /tmp/tmp.xKXGKhXbQt


Warning: Permanently added '[localhost]:3022' (ED25519) to the list of known hosts.
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 391B done
#1 DONE 0.1s

#2 [internal] load metadata for docker.io/library/python:3.8
#2 DONE 0.8s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.1s

#4 [1/4] FROM docker.io/library/python:3.8@sha256:01a4da15f16395a2d17dd9b673ccedcd6a6dbb4e130c8056d0d804dedac11c81
#4 DONE 0.0s

#5 [2/4] WORKDIR /app
#5 CACHED

#6 [internal] load build context
#6 transferring context: 391B done
#6 DONE 0.1s

#7 [3/4] ADD . /app
#7 DONE 0.1s

#8 [4/4] RUN pip install -r requirements.txt
#8 2.751 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
#8 2.965 
#8 2.965 [notice] A new release of pip is available: 23.0.1 -> 24.0
#8 2.965 [notice] To update, run: pip install --upgrade pip
#8 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [4/4] RUN pip install -r requirements.txt:
2.751 ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
2.965 
2.965 [notice] A new release of pip is available: 23.0.1 -> 24.0
2.965 [notice] To update, run: pip install --upgrade pip
------
Dockerfile:11
--------------------
   9 |     
  10 |     # Install any needed packages specified in requirements.txt
  11 | >>> RUN pip install -r requirements.txt
  12 |     
  13 |     # Run the test suite
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
removing docker image...
clearing temp directory
